pull_request_rules:
  - name: automatic merge successful scala-steward PRs
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.3, adopt@1.8)
      - status-success=Build and Test (ubuntu-latest, 2.12.12, adopt@1.8)
    actions:
      merge:
        method: merge
        strict: true
