addSbtPlugin("org.scala-js"           % "sbt-scalajs"                % "1.19.0")
addSbtPlugin("org.portable-scala"     % "sbt-scalajs-crossproject"   % "1.3.2")
addSbtPlugin("com.github.sbt"         % "sbt-dynver"                 % "5.1.0")
addSbtPlugin("com.github.sbt"         % "sbt-ci-release"             % "1.9.3")
addSbtPlugin("io.github.nafg.mergify" % "sbt-mergify-github-actions" % "0.9.0")
